### ISSUE TITLE
fm-index crate ported to vers

### ISSUE THREAD

**Issue by faassen** [Cydhra/vers#17]
I need a FM-index in my XML project.

Unfortunately what I need is a special FM-index that can:

* handle multiple stop symbols $ so that the order of these can be used to give each text a unique id
* the unique text id and the offset of the id is somehow stored in the sampler
* there's also a doc array to obtain a text id given a position in the underlying BWT structure

as described in [Fast in-memory XPath search using compressed indexes](https://doi.org/10.1109/ICDE.2010.5447858), chapter 3 and also 4.2.3 and 4.3. I still haven't fully processed how it all works.

I think those things require a specialized fm-index, so in preparation and in order to increase my understanding I figured I'd try porting the [fm_index crate](https://crates.io/crates/fm-index), originally based around the fid crate, to vers. I'm not sure it helped my understanding a lot yet, but I thought I'd report it here:

https://github.com/faassen/fm-index/tree/vers

I ported things over to vers' BitVec, RsVec and WaveletMatrix (allowing me to remove fm-index's own implementation of wavelet matrix).

There are two test failures I don't understand yet: one in suffix_array and one when testing fm_index with UTF-8 data. (these already happened before I switched over to the waveletmatrix from vers)

Now this is dicey as I'm still getting test failures, but if I run the benches in general construction time has gone up by a little, but count() and locate() have increased their performance by a lot!

```
group                             after                                    before
-----                             -----                                    ------
construction/FMIndex/1000         1.04     59.1±1.56µs        ? ?/sec      1.00     57.0±0.73µs        ? ?/sec
construction/FMIndex/10000        1.03    737.4±4.59µs        ? ?/sec      1.00    716.2±8.12µs        ? ?/sec
construction/FMIndex/100000       1.22      8.9±0.12ms        ? ?/sec      1.00      7.3±0.10ms        ? ?/sec
construction/FMIndex/1000000      1.25     98.0±1.76ms        ? ?/sec      1.00     78.6±1.77ms        ? ?/sec
construction/RLFMIndex/1000       1.01     67.5±4.95µs        ? ?/sec      1.00     67.0±0.50µs        ? ?/sec
construction/RLFMIndex/10000      1.04   795.4±10.27µs        ? ?/sec      1.00   766.1±12.77µs        ? ?/sec
construction/RLFMIndex/100000     1.13      8.9±0.11ms        ? ?/sec      1.00      7.8±0.04ms        ? ?/sec
construction/RLFMIndex/1000000    1.03     97.1±0.88ms        ? ?/sec      1.00     94.2±1.93ms        ? ?/sec
count/FMIndex/0.005               1.00     78.0±1.46µs  3.1 MElem/sec      2.84    222.0±8.29µs 1126.2 KElem/sec
count/FMIndex/0.05                1.00    132.6±0.74µs 1885.8 KElem/sec    3.45    457.9±5.62µs 545.9 KElem/sec
count/FMIndex/0.5                 1.00    133.2±1.57µs 1876.5 KElem/sec    4.03   536.9±12.56µs 465.6 KElem/sec
count/RLFMIndex/0.005             1.00    270.6±4.42µs 923.7 KElem/sec     2.06    557.2±8.91µs 448.7 KElem/sec
count/RLFMIndex/0.05              1.00    479.0±3.47µs 521.9 KElem/sec     2.79  1337.0±23.22µs 187.0 KElem/sec
count/RLFMIndex/0.5               1.00    591.1±3.40µs 422.9 KElem/sec     2.78  1641.3±33.68µs 152.3 KElem/sec
locate/FMIndex/1                  1.00      3.7±0.04ms 67.1 KElem/sec      4.79     17.9±0.28ms 14.0 KElem/sec
locate/FMIndex/2                  1.00      9.8±0.18ms 25.5 KElem/sec      5.40     52.9±0.99ms  4.7 KElem/sec
locate/FMIndex/3                  1.00     21.1±0.31ms 11.9 KElem/sec      5.95    125.6±1.24ms  2037 Elem/sec
locate/RLFMIndex/1                1.00     10.6±0.15ms 23.5 KElem/sec      3.05     32.5±0.23ms  7.7 KElem/sec
locate/RLFMIndex/2                1.00     30.4±0.40ms  8.2 KElem/sec      3.26     98.9±0.67ms  2.5 KElem/sec
locate/RLFMIndex/3                1.00     71.8±0.89ms  3.5 KElem/sec      3.39    243.4±2.15ms  1051 Elem/sec
```

Besides the test failures there is still cleanup to be done: fm-index uses u64 in many places where vers wants usize, and there are a lot of 'as u64' and 'as usize' sprinkled through right now. I want to try updating the various internals to use usize so I can reduce the casting.

There's also some expense during construction time: the WaveletMatrix  originally in fm-index works with vectors of Character, which can be converted from various smaller sizes. In order to use WaveletMatrix from vers I have to convert this to u64 first, and that may involve some extra cost.

I hope to release this as `fm-index-vers` or something like that in the future. `fm-index` hasn't had an update in about 5 years and I think it makes sense to fork it. I'll inform the original author once I choose to do that.

But first those test failures need to be fixed. And I'd like to support my XPath use cases without hindering performance somehow. Maybe you'd like to take a look?

**Comment by Cydhra** [comment]
I will definitely take a look later.

If you need a more convenient constructor for WaveletMatrix, just create a feature request, that should be easy enough. If you're benchmarking make sure to use `-C target-cpu=native` or enable the BMI features manually, because vers benefits *a lot* from them.

About refactoring from u64 to usize: Here you have to estimate costs vs benefits, because I want to migrate to u64 too (because usize makes no sense in a bitvector) but this is also part of #9 because it breaks the API. So this will take some time to happen. However, once it does happen, you can expect a factor 2 speedup of vers' wavelet matrix, so you would probably want to migrate to 2.0.

**Comment by faassen** [comment]
Ah if vers APIs are also likely to change I will keep u64 around for now!

**Comment by Cydhra** [comment]
I wrote two comments onto your commits. [The second one](https://github.com/ajalab/fm-index/commit/15e34b45f6ecac6c3a1ac61e43a69b798f07fe30#r150502871) contains the fix for your failing test cases.

**Comment by faassen** [comment]
Thank you so much! I fixed it now.

Here are the benchmarks (this time on my laptop, so the results will be somewhat different):

```
construction/FMIndex/1000         1.03     45.4±0.93µs        ? ?/sec      1.00     44.2±1.65µs        ? ?/sec
construction/FMIndex/10000        1.02    647.8±3.15µs        ? ?/sec      1.00    635.5±8.88µs        ? ?/sec
construction/FMIndex/100000       1.10      7.8±0.07ms        ? ?/sec      1.00      7.1±0.09ms        ? ?/sec
construction/FMIndex/1000000      1.33    101.8±4.82ms        ? ?/sec      1.00     76.7±2.58ms        ? ?/sec
construction/RLFMIndex/1000       1.09     52.7±2.04µs        ? ?/sec      1.00     48.2±0.78µs        ? ?/sec
construction/RLFMIndex/10000      1.01    686.2±2.54µs        ? ?/sec      1.00    680.5±3.61µs        ? ?/sec
construction/RLFMIndex/100000     1.03      8.0±0.12ms        ? ?/sec      1.00      7.7±0.03ms        ? ?/sec
construction/RLFMIndex/1000000    1.09    101.8±1.87ms        ? ?/sec      1.00     93.7±4.28ms        ? ?/sec
count/FMIndex/0.005               1.00     67.6±1.55µs  3.6 MElem/sec      2.46    166.1±2.72µs 1505.5 KElem/sec
count/FMIndex/0.05                1.00    118.9±4.70µs  2.1 MElem/sec      3.04    360.9±7.14µs 692.7 KElem/sec
count/FMIndex/0.5                 1.00    116.1±2.15µs  2.1 MElem/sec      3.46    402.2±1.76µs 621.5 KElem/sec
count/RLFMIndex/0.005             1.00    232.5±4.62µs 1075.2 KElem/sec    1.91    444.2±6.78µs 562.8 KElem/sec
count/RLFMIndex/0.05              1.00    426.4±9.77µs 586.3 KElem/sec     2.51  1069.7±10.15µs 233.7 KElem/sec
count/RLFMIndex/0.5               1.00   494.0±11.52µs 506.1 KElem/sec     2.60   1285.7±8.28µs 194.4 KElem/sec
locate/FMIndex/1                  1.00      3.2±0.05ms 79.1 KElem/sec      4.49     14.2±0.04ms 17.6 KElem/sec
locate/FMIndex/2                  1.00      8.3±0.02ms 30.1 KElem/sec      4.99     41.4±0.57ms  6.0 KElem/sec
locate/FMIndex/3                  1.00     18.2±0.05ms 13.8 KElem/sec      5.39     97.9±0.35ms  2.6 KElem/sec
locate/RLFMIndex/1                1.00      8.9±0.02ms 28.0 KElem/sec      2.80     25.0±0.08ms 10.0 KElem/sec
locate/RLFMIndex/2                1.00     24.9±0.12ms 10.0 KElem/sec      3.02     75.3±1.13ms  3.3 KElem/sec
locate/RLFMIndex/3                1.00     57.7±0.29ms  4.3 KElem/sec      3.25    187.8±2.91ms  1363 Elem/sec
```

Similar to before.

I will try it with `-C target-cpu=native` next.

**Comment by faassen** [comment]
Here's the one with native, a nice, higher performance boost against before:

```
group                             after-native                             before
-----                             ------------                             ------
construction/FMIndex/1000         1.05     46.5±1.06µs        ? ?/sec      1.00     44.2±1.65µs        ? ?/sec
construction/FMIndex/10000        1.03   657.6±11.59µs        ? ?/sec      1.00    635.5±8.88µs        ? ?/sec
construction/FMIndex/100000       1.14      8.0±0.09ms        ? ?/sec      1.00      7.1±0.09ms        ? ?/sec
construction/FMIndex/1000000      1.27     97.0±1.08ms        ? ?/sec      1.00     76.7±2.58ms        ? ?/sec
construction/RLFMIndex/1000       1.12     54.1±1.16µs        ? ?/sec      1.00     48.2±0.78µs        ? ?/sec
construction/RLFMIndex/10000      1.04    708.1±3.77µs        ? ?/sec      1.00    680.5±3.61µs        ? ?/sec
construction/RLFMIndex/100000     1.05      8.1±0.11ms        ? ?/sec      1.00      7.7±0.03ms        ? ?/sec
construction/RLFMIndex/1000000    1.06     99.3±1.38ms        ? ?/sec      1.00     93.7±4.28ms        ? ?/sec
count/FMIndex/0.005               1.00     47.1±1.12µs  5.2 MElem/sec      3.53    166.1±2.72µs 1505.5 KElem/sec
count/FMIndex/0.05                1.00     75.6±0.53µs  3.2 MElem/sec      4.78    360.9±7.14µs 692.7 KElem/sec
count/FMIndex/0.5                 1.00     86.0±2.29µs  2.8 MElem/sec      4.68    402.2±1.76µs 621.5 KElem/sec
count/RLFMIndex/0.005             1.00    115.3±0.96µs  2.1 MElem/sec      3.85    444.2±6.78µs 562.8 KElem/sec
count/RLFMIndex/0.05              1.00    203.8±1.98µs 1226.9 KElem/sec    5.25  1069.7±10.15µs 233.7 KElem/sec
count/RLFMIndex/0.5               1.00    252.8±3.94µs 988.8 KElem/sec     5.09   1285.7±8.28µs 194.4 KElem/sec
locate/FMIndex/1                  1.00      2.7±0.02ms 93.6 KElem/sec      5.31     14.2±0.04ms 17.6 KElem/sec
locate/FMIndex/2                  1.00      7.1±0.04ms 35.2 KElem/sec      5.84     41.4±0.57ms  6.0 KElem/sec
locate/FMIndex/3                  1.00     15.6±0.08ms 16.0 KElem/sec      6.26     97.9±0.35ms  2.6 KElem/sec
locate/RLFMIndex/1                1.00      5.2±0.02ms 48.5 KElem/sec      4.84     25.0±0.08ms 10.0 KElem/sec
locate/RLFMIndex/2                1.00     14.1±0.06ms 17.7 KElem/sec      5.33     75.3±1.13ms  3.3 KElem/sec
locate/RLFMIndex/3                1.00     31.9±0.09ms  7.8 KElem/sec      5.89    187.8±2.91ms  1363 Elem/sec
```

Here is a straight up comparison between non-native and native:

```
group                             after                                    after-native
-----                             -----                                    ------------
construction/FMIndex/1000         1.00     45.4±0.93µs        ? ?/sec      1.03     46.5±1.06µs        ? ?/sec
construction/FMIndex/10000        1.00    647.8±3.15µs        ? ?/sec      1.02   657.6±11.59µs        ? ?/sec
construction/FMIndex/100000       1.00      7.8±0.07ms        ? ?/sec      1.03      8.0±0.09ms        ? ?/sec
construction/FMIndex/1000000      1.05    101.8±4.82ms        ? ?/sec      1.00     97.0±1.08ms        ? ?/sec
construction/RLFMIndex/1000       1.00     52.7±2.04µs        ? ?/sec      1.03     54.1±1.16µs        ? ?/sec
construction/RLFMIndex/10000      1.00    686.2±2.54µs        ? ?/sec      1.03    708.1±3.77µs        ? ?/sec
construction/RLFMIndex/100000     1.00      8.0±0.12ms        ? ?/sec      1.01      8.1±0.11ms        ? ?/sec
construction/RLFMIndex/1000000    1.02    101.8±1.87ms        ? ?/sec      1.00     99.3±1.38ms        ? ?/sec
count/FMIndex/0.005               1.44     67.6±1.55µs  3.6 MElem/sec      1.00     47.1±1.12µs  5.2 MElem/sec
count/FMIndex/0.05                1.57    118.9±4.70µs  2.1 MElem/sec      1.00     75.6±0.53µs  3.2 MElem/sec
count/FMIndex/0.5                 1.35    116.1±2.15µs  2.1 MElem/sec      1.00     86.0±2.29µs  2.8 MElem/sec
count/RLFMIndex/0.005             2.02    232.5±4.62µs 1075.2 KElem/sec    1.00    115.3±0.96µs  2.1 MElem/sec
count/RLFMIndex/0.05              2.09    426.4±9.77µs 586.3 KElem/sec     1.00    203.8±1.98µs 1226.9 KElem/sec
count/RLFMIndex/0.5               1.95   494.0±11.52µs 506.1 KElem/sec     1.00    252.8±3.94µs 988.8 KElem/sec
locate/FMIndex/1                  1.18      3.2±0.05ms 79.1 KElem/sec      1.00      2.7±0.02ms 93.6 KElem/sec
locate/FMIndex/2                  1.17      8.3±0.02ms 30.1 KElem/sec      1.00      7.1±0.04ms 35.2 KElem/sec
locate/FMIndex/3                  1.16     18.2±0.05ms 13.8 KElem/sec      1.00     15.6±0.08ms 16.0 KElem/sec
locate/RLFMIndex/1                1.73      8.9±0.02ms 28.0 KElem/sec      1.00      5.2±0.02ms 48.5 KElem/sec
locate/RLFMIndex/2                1.76     24.9±0.12ms 10.0 KElem/sec      1.00     14.1±0.06ms 17.7 KElem/sec
locate/RLFMIndex/3                1.81     57.7±0.29ms  4.3 KElem/sec      1.00     31.9±0.09ms  7.8 KElem/sec
```

This lifts up RLFMIndex quite a bit in particular. In general though it's still a lot slower than the FMIndex. If you know, are there space or other benefits to using an RLFMIndex?

**Comment by faassen** [comment]
Concerning the u64 issue: you mention you can't just convert an usize to a u64 or vice versa, you're of course right. But I cannot really escape doing so right now. You mentioned before that in 2.0 you want to change the vers APIs to use u64. Does that mean that you plan to change rank and select to run u64 rather than usize? Even in the original version there were a few usize to u64 conversions, but perhaps not the other way around, which is more dangerous.

I'm happy to migrate to 2.0 once it emerges (if this whole XML library based on this is going anywhere).

**Comment by Cydhra** [comment]
> rank and select to run u64 rather than usize

yes. everything that isn't explicitely an array index will change, since it is more than feasible to have more than 2^32 bits in a vector on 32-bit architectures.

> you mention you can't just convert an usize to a u64 or vice versa

The comment on your commit was meant explicitly for `size_of::<usize>()` because that will change the result of the calculation if usize is smaller than u64, not about casting. Maybe I misunderstood the context of this calculation, but it seemed to me that you wouldn't want to change the type in ``size_of`` just everything else. Could be wrong though.
In general, casts don't really create overhead during runtime, they just make the code less readable and more error-prone, so casting a bit for now is fine.

> If you know, are there space or other benefits to using an RLFMIndex

I don't really know anything about FMIndices, so I have no idea.

**Comment by faassen** [comment]
I've now released [fm-index-vers](https://crates.io/crates/fm-index-vers). Thank you for your help with this!

I've held off on any usize/u64 changes for the time being. I'm eagerly anticipating version 2.0 of Vers! :)

**Comment by faassen** [comment]
I went ahead with the release as the author of fm-index put in a positive emoji. But now there's a comment saying they're open for a PR. I've now opened a PR so it's possible fm-index-vers will have a short life in favor of a vers-backed fm-index.
